### PR TITLE
Fix dependencies for 0.4.0

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
I am removing the `automerge` bot.  This feature isn't safe to use if dependencies or their version constraints change between versions.  In my opinion, it is a feature that should be used exceedingly rarely.  Usually, a person needs to check things.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Shoot!  #24 has incorrect dependency constraints and shouldn't have been merged.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
You forgot to change the build number, so this didn't have an effect.

**Comment by xylar** [comment]
Darn, thanks.  I bumped the build number but then rebased without that commit.

**Pull request merged**
