### PR TITLE
Update recipe from grayskull

### PR DESCRIPTION
**Pull request by xylar**
Add xylar as a maintainer

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #21 and #20

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
It seems like this recipe could use some updating.  An easy and good way to do that is to use [grayskull](https://conda-forge.org/blog/posts/2020-03-05-grayskull/) as I've done here.  It added several tests that are a good idea, including `pip check`.  It removed some dependencies and version restrictions that I agree are likely unneeded.

**Comment by xylar** [comment]
@conda-forge/sshtunnel, this is ready to merge whenever you get a chance.  Thanks!

**Comment by basnijholt** [comment]
Thanks, LGTM!

**Pull request merged**
